version: '3.4'

services:
   cointracker.sql:
    image: mcr.microsoft.com/mssql/server
    environment:
        - SA_PASSWORD=Password123
        - ACCEPT_EULA=Y
    ports:
        - "5435:1433"
    networks:
    - cointracker
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s
   app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: App/Dockerfile
    environment:
      - ConnectionStrings__Database=Server=cointracker.sql;Database=CoinTracker;User=sa;Password=Password123;Encrypt=False
    depends_on:
        app.migration:
            condition: service_completed_successfully
    ports:
        - "8080:8080"
    networks:
        - cointracker
   app.migration:
    image: ${DOCKER_REGISTRY-}app-migration
    build:
      context: .
      dockerfile: App/Migration/Dockerfile
    environment:
      - ConnectionStrings__Database=Server=cointracker.sql;Database=CoinTracker;User=sa;Password=Password123;Encrypt=False
    depends_on:
        cointracker.sql:
            condition: service_healthy
    networks:
        - cointracker
networks:
  cointracker:
