# Dockerfile-migration

# Usa un'immagine che contiene gli strumenti necessari per eseguire le migrazioni del database
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration

# Copia il codice dell'applicazione
WORKDIR /app
COPY . .

# Esegui le migrazioni del database
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
CMD dotnet ef database update --project CoinList.Infrastrcture/CoinList.Infrastrcture.csproj --startup-project App/App.csproj
