name: BuildAndTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Compose version
        run: docker-compose --version
        
      - name: Add Docker Compose to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Check Docker Compose version
        run: docker-compose --version
