name: BuildAndTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose installation
        run: docker-compose --version
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Install SonarScanner for MSBuild
        run: |
          curl -sSLo sonar-scanner-msbuild.exe https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.8/sonar-scanner-msbuild-4.8.0.3126-net46.zip
          unzip sonar-scanner-msbuild.exe
          export PATH=$PATH:$(pwd)/sonar-scanner-msbuild-4.8.0.3126-net46/bin
    
      - name: Restore
        run: dotnet restore ./CoinTrackerNew.sln
      
      - name: Build
        run: dotnet build ./CoinTrackerNew.sln --configuration Release --no-restore

      - name: Begin SonarQube analysis
        run: |
          sonar-scanner begin /k:"Sas1989_CoinTrackerNew" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io

      - name: Unit Test
        run: dotnet test ./CoinTrackerNew.sln --configuration Release --no-restore --no-build

      - name: Acceptance test
        run: dotnet test ./CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest.sln --configuration Release
