name: BuildAndTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose installation
        run: docker-compose --version
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
          
      - name: Check Docker Compose version
        run: docker compose version
        
      - name: Restore
        run: dotnet restore ./CoinTrackerNew.sln
      
      - name: Build
        run: dotnet build ./CoinTrackerNew.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./CoinTrackerNew.sln --configuration Release --no-restore --no-build
      
      - name: Acceptance test Restore
        run: dotnet restore ./CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest.sln 
  
      - name: Acceptance test Build
        run: dotnet build ./CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest.sln --configuration Release --no-restore 

      - name: Acceptance test
        run: dotnet test ./CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest.sln --configuration Release --no-restore --no-build
      
      - name: Show SQL Server logs (if needed)
        run: docker ps
        if: failure()
