name: BuildAndTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose installation
        run: docker-compose --version
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
    
      - name: Restore
        run: dotnet restore ./CoinTrackerNew.sln
      
      - name: Build
        run: dotnet build ./CoinTrackerNew.sln --configuration Release --no-restore
 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'openjdk' # Alternative distribution options are available. 
          
      - name: Check Java version
        run: java -version
 
      - name: Setup SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Begin SonarQube analysis
        run: |
          sonar-scanner begin /k:"Sas1989_CoinTrackerNew" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io

      - name: Unit Test
        run: dotnet test ./CoinTrackerNew.sln --configuration Release --no-restore --no-build

      - name: End SonarCloud analysis
        run: sonar-scanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Acceptance test
        run: dotnet test ./CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest.sln --configuration Release
