name: BuildAndTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Verify Docker Compose installation
        run: docker-compose --version
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Setup SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: Sas1989_CoinTrackerNew
          token: ${{ secrets.SONAR_TOKEN }}
    
      - name: Restore
        run: dotnet restore ./CoinTrackerNew.sln
      
      - name: Build
        run: dotnet build ./CoinTrackerNew.sln --configuration Release --no-restore

      - name: Begin SonarQube analysis
        run: |
          sonar-scanner begin /k:"Sas1989_CoinTrackerNew" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io

      - name: Unit Test
        run: dotnet test ./CoinTrackerNew.sln --configuration Release --no-restore --no-build

      - name: End SonarCloud analysis
        run: sonar-scanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Acceptance test
        run: dotnet test ./CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest/CoinTracker.AcceptanceTest.sln --configuration Release
