name: BuildAndTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Compose path
        run: which docker-compose

      - name: Set Docker Compose path environment variable
        run: echo "DOCKER_COMPOSE_PATH=$(which docker-compose)" >> $GITHUB_ENV

      - name: Check Docker Compose version
        run: docker-compose --version
